all:
	clear
#	gcc main.c -o exe
#	gcc mouse.c -o exe
#	gcc meta.c proc_grafico.s mouse.c -o exe
#	gcc ovni.c proc_grafico.s -o exe
#	gcc menu.c proc_grafico.s -o exe
#	gcc lab_v2.c -o exe -std=c99
#	gcc teste.c proc_grafico.s mouse.c -o exe -std=c99 
#add ao final do gcc acima -Wall
#que isso
	gcc labirintoVGA.c proc_grafico.s mouse.c -pthread -o exe -std=c99
#	gcc labirintoVGA.c proc_grafico.s mouse.c -lpthread -o exe -std=c99
	sudo ./exe