all:
	clear
#	gcc main.c -o exe
#	gcc mouse.c -o exe
#	gcc meta.c proc_grafico.s mouse.c -o exe
#	gcc ovni.c proc_grafico.s -o exe
#	gcc menu.c proc_grafico.s -o exe
#	gcc animacao_menu.c proc_grafico.s -o exe
#	gcc lab_v2.c -o exe -std=c99
#	gcc labirintoVGA.c proc_grafico.s mouse.c -o exe -std=c99 

	gcc jogo_com_threads.c proc_grafico.s mouse_thread.c -o exe -std=c99 -pthread

#	gcc mouse_thread.c -o exe -std=c99


#	gcc animacao_portal.c proc_grafico.s -o exe
#add ao final do gcc acima -Wall
	sudo ./exe